import { NextResponse } from "next/server";
import { serviceClient, hasDatabase } from "@/lib/db/client";

/**
 * ANALYTICS — the Data Analyst layer, computed from real rows.
 *
 * Every figure here is an aggregate over funnel_events and escalations. There
 * is no code path that renders a number someone typed in, which is the same
 * rule the patient-facing <LiveStat> follows. A product that argues for honest
 * numbers has to have an honest dashboard.
 *
 * WHAT MAKES THIS MORE THAN A BAR CHART
 * -------------------------------------
 * Stage totals hide the thing a clinic actually needs. What matters is the
 * TRANSITIONS — where people leave — so conversion and loss are reported per
 * step, and the single worst drop-off is named rather than left to be spotted.
 *
 * PHI: funnel_events.metadata_json is PHI-free by construction. That is what
 * justifies keeping it 30 days when guest chat content is destroyed at 7.
 *
 * SYNTHETIC DATA IS LABELLED. Rows generated by scripts/replay_traffic.py carry
 * metadata_json->>synthetic, and the response says how many of the rows behind
 * every number are synthetic. A dashboard that silently mixes generated and real
 * traffic is worse than no dashboard.
 */

/**
 * THE FUNNEL IS NOT A LINE, AND TREATING IT AS ONE PRODUCES A PHANTOM.
 *
 * The first version of this ran conversion across all seven stages in order,
 * signup included. Every channel then reported the same "biggest drop-off":
 * value_event → auth_started, 0% carried, hundreds lost. That finding was an
 * artefact, not a result. A guest who reaches a nurse never signs up — the
 * whole premise is that care comes before an account — so the signup stages
 * are legitimately empty on the path that WORKS.
 *
 * Reported as a phantom, it would have pointed a clinic at fixing a signup
 * form that nobody was supposed to reach. So the main path stops at
 * escalation_sent, and account creation is reported separately as the optional
 * branch it actually is.
 */
const MAIN_PATH = [
  "visitor",
  "conversation_started",
  "value_event",
  "escalation_sent",
] as const;

/** Optional. Entered only when someone chooses to create an account. */
const ACCOUNT_BRANCH = ["auth_started", "consented", "patient_created"] as const;

const ALL_STAGES = [...MAIN_PATH, ...ACCOUNT_BRANCH] as const;

interface EventRow {
  event_type: string;
  lead_session_id: string | null;
  created_at: string;
  metadata_json: Record<string, unknown> | null;
}

export async function GET(request: Request) {
  const url = new URL(request.url);
  const days = Math.min(Number(url.searchParams.get("days") ?? 30), 365);

  if (!hasDatabase()) {
    return NextResponse.json(
      {
        error: "database_not_configured",
        detail:
          "SUPABASE_SERVICE_ROLE_KEY is not set. This dashboard is deliberately " +
          "empty rather than seeded with sample data — a fabricated dashboard " +
          "would contradict the rule the product is built on.",
      },
      { status: 503 },
    );
  }

  const since = new Date(Date.now() - days * 864e5).toISOString();
  const db = serviceClient();

  const [{ data: events }, { data: escalations }] = await Promise.all([
    db
      .from("funnel_events")
      .select("event_type, lead_session_id, created_at, metadata_json")
      .gte("created_at", since)
      .order("created_at", { ascending: true })
      .limit(20000),
    db
      .from("escalations")
      .select("id, status, created_at, sla_due_at, triage_summary, acquisition_context_json")
      .gte("created_at", since)
      .limit(5000),
  ]);

  const rows = (events ?? []) as EventRow[];

  // ---- Provenance of the numbers themselves ------------------------------
  const synthetic = rows.filter((r) => r.metadata_json?.synthetic === true).length;

  // ---- Per-channel funnel with drop-off ----------------------------------
  const byChannel = new Map<string, Map<string, Set<string>>>();
  const sessionFirstSeen = new Map<string, string>();
  const sessionLast = new Map<string, { stage: string; at: string; channel: string; risk?: string }>();

  for (const e of rows) {
    if (!e.lead_session_id) continue;
    const meta = e.metadata_json ?? {};
    const channel = String(meta.source_channel ?? "unknown");

    const stages = byChannel.get(channel) ?? new Map<string, Set<string>>();
    const set = stages.get(e.event_type) ?? new Set<string>();
    set.add(e.lead_session_id);
    stages.set(e.event_type, set);
    byChannel.set(channel, stages);

    if (!sessionFirstSeen.has(e.lead_session_id)) {
      sessionFirstSeen.set(e.lead_session_id, e.created_at);
    }
    sessionLast.set(e.lead_session_id, {
      stage: e.event_type,
      at: e.created_at,
      channel,
      risk: (meta.risk_level as string) ?? sessionLast.get(e.lead_session_id)?.risk,
    });
  }

  const funnels = [...byChannel.entries()]
    .map(([channel, stages]) => {
      const counts: Record<string, number> = {};
      for (const s of ALL_STAGES) counts[s] = stages.get(s)?.size ?? 0;

      // Conversion is measured along the main path only.
      const steps = MAIN_PATH.slice(0, -1)
        .map((from, i) => {
          const to = MAIN_PATH[i + 1];
          const a = counts[from];
          const b = counts[to];
          if (a === 0) return null;
          return { from, to, rate: Number((b / a).toFixed(3)), lost: Math.max(0, a - b) };
        })
        .filter((s): s is NonNullable<typeof s> => s !== null && (s.lost > 0 || s.rate > 0));

      const worst = [...steps].sort((a, b) => b.lost - a.lost)[0] ?? null;
      const entered = counts.visitor || 0;
      const finished = counts.escalation_sent || 0;

      return {
        channel,
        stages: counts,
        steps,
        biggest_drop_off: worst,
        entered,
        completed: finished,
        completion_rate: entered ? Number((finished / entered).toFixed(3)) : null,
        // Reported, never mixed into the conversion figures above. Zero here
        // means nobody chose to create an account — which on the guest path is
        // the expected outcome, not a failure.
        account_branch: Object.fromEntries(
          ACCOUNT_BRANCH.map((s) => [s, counts[s]]),
        ),
      };
    })
    .sort((a, b) => b.entered - a.entered);

  // ---- Where sessions actually die ---------------------------------------
  // Instrumented, not guessed. The brief asks us to explain abandonment, and
  // "we think people leave at signup" is not an answer.
  const abandonment = new Map<string, number>();
  for (const [, last] of sessionLast) {
    if (last.stage === "escalation_sent" || last.stage === "patient_created") continue;
    const key = `${last.channel}::${last.stage}`;
    abandonment.set(key, (abandonment.get(key) ?? 0) + 1);
  }

  // ---- Risk mix ----------------------------------------------------------
  const riskMix: Record<string, number> = { low: 0, medium: 0, high: 0 };
  for (const [, last] of sessionLast) {
    if (last.risk && last.risk in riskMix) riskMix[last.risk] += 1;
  }

  // ---- SLA performance ---------------------------------------------------
  const now = Date.now();
  const esc = escalations ?? [];
  const overdue = esc.filter(
    (e) => e.sla_due_at && new Date(e.sla_due_at).getTime() < now && e.status === "sent",
  );

  // ---- Time-to-value: how long before someone gets something useful ------
  const timeToValue: number[] = [];
  for (const e of rows) {
    if (e.event_type !== "value_event" || !e.lead_session_id) continue;
    const first = sessionFirstSeen.get(e.lead_session_id);
    if (!first) continue;
    const mins = (new Date(e.created_at).getTime() - new Date(first).getTime()) / 60000;
    if (mins >= 0 && mins < 240) timeToValue.push(mins);
  }
  timeToValue.sort((a, b) => a - b);
  const median = timeToValue.length
    ? Number(timeToValue[Math.floor(timeToValue.length / 2)].toFixed(1))
    : null;

  return NextResponse.json({
    window_days: days,
    provenance: {
      events_analysed: rows.length,
      synthetic_events: synthetic,
      // Say it plainly wherever it is true.
      note:
        synthetic > 0
          ? `${synthetic} of ${rows.length} events are SYNTHETIC (scripts/replay_traffic.py). ` +
            `Distributions were assumed, not measured — treat every figure as illustrative.`
          : null,
    },
    totals: {
      sessions: sessionLast.size,
      escalations: esc.length,
      overdue_escalations: overdue.length,
      median_minutes_to_value: median,
    },
    risk_mix: riskMix,
    funnels,
    abandonment: [...abandonment.entries()]
      .map(([key, count]) => {
        const [channel, lastEvent] = key.split("::");
        return { channel, last_event: lastEvent, count };
      })
      .sort((a, b) => b.count - a.count),
    escalation_status: esc.reduce<Record<string, number>>((acc, e) => {
      acc[e.status] = (acc[e.status] ?? 0) + 1;
      return acc;
    }, {}),
  });
}
